apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mumu-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myNginx
      release: canary
  template:
    metadata:
      labels:
        app: myNginx
        release: canary
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.15.7
        ports:
        - name: http
          containerPort: 80
          