apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment2
  namespace: mumu-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
      - name: nginx
        image: index.tenxcloud.com/docker_library/nginx:1.7.9
        resources:
          requests:
            memory: "30G"
            cpu: "10"
          limits:
            memory: "100G"
            cpu: "90"
        ports:
        - containerPort: 80