apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment2
  namespace: mumu-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
      - name: nginx
        image: index.tenxcloud.com/docker_library/nginx:1.7.9
        resources:
          requests:
            memory: "256m"
            cpu: "0.2"
          limits:
            memory: "1G"
            cpu: "1"
        ports:
        - containerPort: 80