apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: mumu-ns
spec:
  limits:
  - default:
      memory: 3Gi
      cpu: 3
    defaultRequest:
      memory: 256Mi
      cpu: 1
    type: Container