apiVersion: v1
kind: Pod
metadata:
  name: liveness-httpGet
  namespace: mumu-ns
  labels:
    app: mumuapp
    tier: webserver
spec:
  containers:
    - name: mynginx
      image: nginx:1.15.7
      resources:
        requests:
          cpu: 0.1
          memory: "256m" 
        limits:
          cpu: 1
          memory: 1G
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
      livenessProbe:
        httpGet:
          port: http
        initialDelaySeconds: 1
        periodSeconds: 3
