apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: mumu-ns
  labels:
    app: mumuapp
    tier: webserver
spec:
  containers:
    - name: mynginx
      image: nginx:1.15.7
      ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
